# Generated by Django 5.2.8 on 2025-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_personalizedtest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
